### PR TITLE
Fix openzipkin/zipkin-dependencies/issues/192

### PR DESCRIPTION
**Pull request by dankolt**

### CODE REVIEW

**Comment by jorgheymans** [comment]
Can you explain a bit what it is you're trying to fix here ?

**Comment by dankolt** [comment]
> Can you explain a bit what it is you're trying to fix here ?

Bug describes in https://github.com/openzipkin/zipkin-dependencies/issues/192.
When we start dependencies container crond interrupts with message:
`crond[1]: root: Permission denied`
It happens because crond starts by zipkin-dependencies user but scripts copied in Dockerfile with root owner.
So I changed this behaviour and dependencies job start working now.

**Comment by jorgheymans** [comment]
Thanks for the clarification! @shakuzen are you ok with this fix ?

**Comment by shakuzen** [comment]
> Error:  Failed to execute goal com.mycila:license-maven-plugin:4.0.rc2:check (default) on project zipkin-dependencies-parent: Some files do not have the expected license header

I am guessing the license header end year of the Dockerfile needs to be extended to 2021.

Otherwise, LGTM.

**Comment by dankolt** [comment]
> > Error:  Failed to execute goal com.mycila:license-maven-plugin:4.0.rc2:check (default) on project zipkin-dependencies-parent: Some files do not have the expected license header
> 
> I am guessing the license header end year of the Dockerfile needs to be extended to 2021.
> 
> Otherwise, LGTM.

Exactly! Thanks!

**Comment by ipavlushin** [comment]
Hi @jorgheymans @shakuzen !
Could you also build and push Docker image with these changes?

**Pull request merged**
