### PR TITLE
Updates integration tests to Jupiter

### PR DESCRIPTION
**Pull request by adriancole**
Zipkin 2.16 migrated integration tests used here to Jupiter, hence more
change than usual. One other change here is using mysql via docker
instead of relying on a standalone install.

cc @anuraaga

### CODE REVIEW

**Comment by adriancole** [comment]
I'm not sure you really want to put the spark job into the place everybody needs to maintain :)

part of this is a matter of blast radius. Massive refactors often dont' imply so much work, just they do more when we start to share libraries that have high rates of change.

**Comment by adriancole** [comment]
this repo would cripple others, also. it is stuck on an ancient version of JDK due to spark etc.

not the best issue to discuss, but zipkin-aws is also much less supported than our core repo, as you probably noticed that it is sortof a "when I have time" type of thing. We have to be careful about overloading the parts of our org that must work with work that is of mixed maintenance and use.

**Comment by adriancole** [comment]
sometimes zipkin-aws isn't released and no one would ever notice, in other words. Same here. It feels different having just done massive refactoring, but yeah usually it is neglected because people don't have time to deal with it, and don't need to. We don't want to move neglect into the main repo as it could get us into a even harder place of getting things to work.

**Comment by anuraaga** [comment]
Thanks - wasn't thinking about the actual JDK dependencies too, but it makes sense to separate different ones :)

**Pull request merged**
